{
 "title": "Kafka Worker Pool",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_consumergroup_lag_sum{consumergroup=\"$group\"},topic)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(kafka_consumergroup_lag_sum,consumergroup)"
    }
   },
   { "name": "instance", "query": { "query": "label_values(up,instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Health / Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"go_worker_pool\", instance=~\"$instance\"}\r\n",
     "legendFormat": "App Up"
    },
    {
     "expr": "up{job=\"kafka_exporter\"}\r\n",
     "legendFormat": "Kafka Exporter Up"
    },
    { "expr": "kafka_brokers\r\n", "legendFormat": "Brokers" }
   ]
  },
  {
   "title": "Kafka Consumer Group（Lag / Members / Offsets）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumergroup_members{consumergroup=\"$group\"}\r\n",
     "legendFormat": "Group Members"
    },
    {
     "expr": "kafka_consumergroup_lag_sum{consumergroup=\"$group\", topic=\"$topic\"}\r\n",
     "legendFormat": "Total Lag"
    },
    {
     "expr": "kafka_consumergroup_lag{consumergroup=\"$group\", topic=\"$topic\"}\r\n",
     "legendFormat": "Lag by Partition p={{partition}}"
    },
    {
     "expr": "kafka_consumergroup_current_offset{consumergroup=\"$group\", topic=\"$topic\"}\r\n",
     "legendFormat": "Current Offset by Partition  p={{partition}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(my_system_worker_pool_producer_sent_total[$__rate_interval]))\r\n",
     "legendFormat": "Producer RPS"
    },
    {
     "expr": "sum(rate(my_system_worker_pool_consumer_processed_total[$__rate_interval]))\r\n",
     "legendFormat": "Consumer Processed RPS"
    },
    {
     "expr": "sum(rate(my_system_worker_pool_consumer_errors_total[$__rate_interval]))\r\n",
     "legendFormat": "Error RPS"
    },
    {
     "expr": "sum(rate(my_system_worker_pool_rate_limited_total[$__rate_interval]))\r\n",
     "legendFormat": "Rate Limited RPS"
    }
   ]
  },
  {
   "title": "DLQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"${topic}-dlq\"}[$__rate_interval]))\r\n",
     "legendFormat": "DLQ Publish RPS"
    },
    {
     "expr": "(\r\n  sum(rate(kafka_topic_partition_current_offset{topic=~\"${topic}-dlq\"}[5m]))\r\n)\r\n/\r\nclamp_min(\r\n  sum(rate(kafka_topic_partition_current_offset{topic=\"$topic\"}[5m])),\r\n  1\r\n)\r\n",
     "legendFormat": "DLQ Ratio（DLQ / Input）"
    }
   ]
  },
  {
   "title": "Latency（p95/p99）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(my_system_worker_pool_consumer_duration_seconds_bucket[$__rate_interval])) by (le)\r\n)\r\n",
     "legendFormat": "Consumer p95"
    },
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum(rate(my_system_worker_pool_consumer_duration_seconds_bucket[$__rate_interval])) by (le)\r\n)\r\n",
     "legendFormat": "Consumer p99"
    }
   ]
  },
  {
   "title": "Kafka Topic / Partition Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "kafka_topic_partitions{topic=\"$topic\"}\r\n",
     "legendFormat": "Partitions"
    },
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{topic=\"$topic\"})\r\n",
     "legendFormat": "Under Replicated Partitions"
    },
    {
     "expr": "min(kafka_topic_partition_in_sync_replica{topic=\"$topic\"})\r\n",
     "legendFormat": "Min ISR"
    }
   ]
  },
  {
   "title": "Backpressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max(my_system_worker_pool_consumer_queue_length)\r\n",
     "legendFormat": "In-process Queue Length（Gauge）"
    },
    {
     "expr": "max(my_system_worker_pool_consumer_inflight)\r\n",
     "legendFormat": "In-flight（Gauge）"
    },
    {
     "expr": "max(my_system_worker_pool_consumer_inflight) / 50\r\n",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "title": "CPU (cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"go_worker_pool\", instance=\"host.docker.internal:8080\"}[1m])",
     "legendFormat": "CPU (cores)"
    }
   ]
  },
  {
   "title": "RSS (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"go_worker_pool\", instance=\"host.docker.internal:8080\"} / 1024 / 1024",
     "legendFormat": "RSS (MiB)"
    }
   ]
  }
 ]
}